const quotes = [
  '"Success is not final, failure is not fatal: It is the courage to continue that counts." - Winston Churchill',
  '"The only way to do great work is to love what you do." - Steve Jobs',
  '"The future belongs to those who believe in the beauty of their dreams." - Eleanor Roosevelt',
  '"Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful." - Albert Schweitzer',
  '"The only place where success comes before work is in the dictionary." - Vidal Sassoon',
  '"Believe you can and you\'re halfway there." - Theodore Roosevelt',
  "\"Your time is limited, don't waste it living someone else's life.\" - Steve Jobs",
  '"I find that the harder I work, the more luck I seem to have." - Thomas Jefferson',
  '"The secret to success is to know something nobody else knows." - Aristotle Onassis',
  '"Success is not just about making money. It\'s about making a difference." - Unknown',
  '"Success is walking from failure to failure with no loss of enthusiasm." - Winston Churchill',
  '"The road to success and the road to failure are almost exactly the same." - Colin R. Davis',
  '"Don\'t watch the clock; do what it does. Keep going." - Sam Levenson',
  '"Success usually comes to those who are too busy to be looking for it." - Henry David Thoreau',
  '"Don\'t be afraid to give up the good to go for the great." - John D. Rockefeller',
  '"The only limit to our realization of tomorrow will be our doubts of today." - Franklin D. Roosevelt',
  '"Success is not in what you have, but who you are." - Bo Bennett',
  '"The harder you work for something, the greater you\'ll feel when you achieve it." - Unknown',
  '"The only thing standing between you and your goal is the story you keep telling yourself as to why you can\'t achieve it." - Jordan Belfort',
  '"Opportunities don\'t happen. You create them." - Chris Grosser',
  '"Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart." - Roy T. Bennett',
  '"Success is not the result of spontaneous combustion. You must set yourself on fire." - Arnold H. Glasow',
  '"The best revenge is massive success." - Frank Sinatra',
  '"Learning is a treasure that will follow its owner everywhere." - Chinese Proverb',
  '"The beautiful thing about learning is that no one can take it away from you." - B.B. King',
  '"In learning you will teach, and in teaching you will learn." - Phil Collins',
  '"The more that you read, the more things you will know. The more that you learn, the more places you\'ll go." - Dr. Seuss',
  '"Education is the passport to the future, for tomorrow belongs to those who prepare for it today." - Malcolm X',
  '"The journey of a thousand miles begins with one step." - Lao Tzu',
  '"Learning never exhausts the mind." - Leonardo da Vinci',
];

export default quotes;
